### ISSUE TITLE
Crashing on AD 3 final

### ISSUE THREAD

**Issue by Paul-Vdp** [efficiosoft/hass-apps#12]
After I upgraded AD to version 3 (final) Heaty crashes on every reschedule :

2018-03-21 12:16:23.014598 WARNING AppDaemon: Unexpected error in worker for App heaty:
2018-03-21 12:16:23.015474 WARNING AppDaemon: Worker Ags: {'type': 'timer', 'function': <bound method HeatyApp._publish_state_timer_cb of <hass_apps.heaty.app.HeatyApp object at 0x751befb0>>, 'kwargs': {}, 'name': 'heaty', 'id': UUID('7bf255f0-4c64-4acc-823c-dc9768d91ebf')}
2018-03-21 12:16:23.016163 WARNING AppDaemon: ------------------------------------------------------------
2018-03-21 12:16:23.017840 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 529, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/srv/homeassistant/lib/python3.5/site-packages/hass_apps/heaty/app.py", line 120, in _publish_state_timer_cb
    self.publish_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/hass_apps/heaty/app.py", line 276, in publish_state
    self.set_app_state(entity_id, state)
  File "/srv/homeassistant/lib/python3.5/site-packages/hass_apps/common.py", line 105, in set_app_state
    self.AD.set_app_state(entity_id, state)
TypeError: set_app_state() missing 1 required positional argument: 'state'

This is the same error as reported on the forum by jo-me ...

**Comment by efficiosoft** [comment]
Just for reference, here is the issue:

https://github.com/home-assistant/appdaemon/issues/256

**Comment by efficiosoft** [comment]
Version 3.0.0 is now blacklisted and won't get installed as a dependency for hass-apps anymore. You can install the 3.0.0b5 explicitly instead.
