### ISSUE TITLE
Missing 'observable' module in AppDaemon docker container

### ISSUE THREAD

**Issue by dzerovibe** [efficiosoft/hass-apps#17]
I just tried running Heaty, but got the following error. I’m running hass.io (HA v0.76.2) on a Raspberry Pi 3 B+.

Appdaemon seems to work, as I can see the dashboard with the Hello World tile. But heaty fails to start:

`
2018-08-28 20:57:01.182447 INFO AppDaemon: Initializing app heaty_minimal using class HeatyApp from module hass_apps_loader
2018-08-28 20:57:01.464473 WARNING AppDaemon: ------------------------------------------------------------
2018-08-28 20:57:01.465569 WARNING AppDaemon: Unexpected error initializing app: heaty_minimal:
2018-08-28 20:57:01.467230 WARNING AppDaemon: ------------------------------------------------------------
2018-08-28 20:57:01.489820 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2040, in check_app_updates
    self.init_object(app)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1565, in init_object
    self, name, self.logger, self.error, app_args, self.config, self.app_config, self.global_vars
  File "/config/appdaemon/apps/hass_apps/loader.py", line 28, in _proxy_loader
    app_mod = _import_app_module(app_package)
  File "/config/appdaemon/apps/hass_apps/loader.py", line 24, in _import_app_module
    return importlib.import_module(mod_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2018-08-28 20:57:01.497488 INFO AppDaemon: App initialization complete
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/hass_apps/heaty/app.py", line 18, in <module>
    from . import __version__, config, expr, util
  File "/config/appdaemon/apps/hass_apps/heaty/config.py", line 10, in <module>
    from .room import Room
  File "/config/appdaemon/apps/hass_apps/heaty/room.py", line 16, in <module>
    from .window_sensor import WindowSensor
  File "/config/appdaemon/apps/hass_apps/heaty/window_sensor.py", line 10, in <module>
    import observable
ModuleNotFoundError: No module named 'observable'
2018-08-28 20:57:01.490814 WARNING AppDaemon: ------------------------------------------------------------
`

**Comment by dzerovibe** [comment]
Thanks for the speedy response! Heaty seems to be working fine now on my system :-)

**Comment by efficiosoft** [comment]
Nice to hear. Wish you all the best.
