### ISSUE TITLE
Heaty fails to start on hassio

### ISSUE THREAD

**Issue by taste66** [efficiosoft/hass-apps#21]
I am trying to get Heaty running on my docker based hassio installation.
Appdaemon runs fine and I get the output from the hello.py 
However when adding the heaty.yaml I run into an error. I used the heaty_minimal with only a few changes. This is the info:
Running HA 0.82.1
Content heaty.yaml:

```
# This is a minimal example configuration that does just basic things.
# If you want to have further control over your heatings, use open window
# detection, set temperature based on entity states etc., please see the
# full example below.
heaty_minimal:
  # Obligatory settings that tell appdaemon where to find the app.
  # You shouldn't need to change these two.
  module: hass_apps_loader
  class: HeatyApp

  rooms:

    # Define such a block for each room you want to control.
    living:
      thermostats:
        climate.boiler_heat:
      schedule:
      # From Monday to Friday, set temperature to 20.5 °C from 7.45 am
      # to 10.00 pm.
      - { temp: 20.5, start: "07:45", end: "22:00", weekdays: 1-5 }
      # On weekends, set temperature to 20.5 °C from 8.15 am to 11.30 pm.
      - { temp: 20.5, start: "08:15", end: "23:30", weekdays: "6,7" }
      # At all other times, set temperature to 16 °C.
      - { temp: 16 }

```

log output of Appdaemon
```
2018-11-18 12:40:21.641439 INFO AppDaemon Version 3.0.2 starting
2018-11-18 12:40:21.641745 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2018-11-18 12:40:21.643192 INFO AppDaemon: Starting Apps
2018-11-18 12:40:21.646479 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-11-18 12:40:21.750970 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-11-18 12:40:21.751556 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-11-18 12:40:21.751878 INFO Starting Dashboards
2018-11-18 12:40:21.758999 INFO API is disabled
2018-11-18 12:40:21.766989 INFO AppDaemon: HASS: Connected to Home Assistant 0.82.1
2018-11-18 12:40:21.903200 INFO AppDaemon: Got initial state from namespace default
2018-11-18 12:40:23.856709 INFO AppDaemon: Reading config
2018-11-18 12:40:23.870604 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2018-11-18 12:40:23.870839 INFO AppDaemon: /config/appdaemon/apps/heaty.yaml added or modified
2018-11-18 12:40:23.871003 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2018-11-18 12:40:23.871162 INFO AppDaemon: /config/appdaemon/apps/heaty.yaml added or modified
2018-11-18 12:40:23.871323 INFO AppDaemon: App 'hello_world' added
2018-11-18 12:40:23.871483 INFO AppDaemon: App 'heaty_minimal' added
2018-11-18 12:40:23.871773 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2018-11-18 12:40:23.872302 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hass_apps_loader.py
2018-11-18 12:40:23.874103 WARNING AppDaemon: ------------------------------------------------------------
2018-11-18 12:40:23.874262 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/hass_apps_loader.py:
2018-11-18 12:40:23.874425 WARNING AppDaemon: ------------------------------------------------------------
2018-11-18 12:40:23.878432 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/hass_apps_loader.py", line 1, in <module>
    from hass_apps.loader import *
ModuleNotFoundError: No module named 'hass_apps'

2018-11-18 12:40:23.878734 WARNING AppDaemon: Removing associated apps:
2018-11-18 12:40:23.878602 WARNING AppDaemon: ------------------------------------------------------------
2018-11-18 12:40:23.878882 WARNING AppDaemon: heaty_minimal
2018-11-18 12:40:23.879150 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2018-11-18 12:40:23.890398 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2018-11-18 12:40:23.983576 INFO hello_world: Hello Marc from AppDaemon
2018-11-18 12:40:23.984858 INFO hello_world: You are now ready to run Apps!
2018-11-18 12:40:23.985516 INFO AppDaemon: App initialization complete
```

As you can see I modified the hello_word app to be absolutely sure it ran from the appdaemon/apps directory. Next to this I tried to copy the hass_apps from
`/usr/share/hassio/homeassistant/appdaemon/venv/lib/python3.5/site-packages/hass_apps` to `config/appdaemon/apps` but this only increased the #errors

any tips to further debug this?

**Comment by taste66** [comment]
Hi Robert,

Thanks a lot for your answer. I did follow that guide although not immediately from the start. I will remove appdaemon and the Heaty files and start over tomorrow, (unfortunately do not have time now).
Thanks for the tip on Schedy, will look into that.
Marc

**Comment by taste66** [comment]
Hi Robert,

I fully started over, purge the appdaemon docker container and resinstalled from hass.io It does run again and my hello world is working. I do have the requirements.txt file with hass-apps in it (had that the last time too) I did not run the script to get the hass-apps since I guess the hass_app_loader.py should do this but this does not seem to work. I have no idea what I miss here must be something obvious.
This is output of my log:
```
2018-11-19 21:53:11.498080 INFO AppDaemon: HASS: Connected to Home Assistant 0.82.1
2018-11-19 21:53:11.631600 INFO AppDaemon: Got initial state from namespace default
2018-11-19 21:53:13.584494 INFO AppDaemon: Reading config
2018-11-19 21:53:13.586888 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2018-11-19 21:53:13.587039 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2018-11-19 21:53:13.587174 INFO AppDaemon: App 'hello_world' added
2018-11-19 21:53:13.587372 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2018-11-19 21:53:13.587887 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hass_apps_loader.py - ignoring
2018-11-19 21:53:13.588042 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2018-11-19 21:53:13.600368 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
```

**Comment by efficiosoft** [comment]
Yeah, the hassio appdaemon add-on isn't built ontop of the official appdaemon docker container, which is why the requirements.txt support isn't there.

I noticed this as well and again updated the docs to reflect this. There's now a section specific to hassio. Would you mind trying it again? It's just one line to add to your add-on settings.

**Comment by taste66** [comment]
I'm really sorry I do not have a good clue where to add the configuration:
```
"python_packages": [
    "hass-apps"
]
```
I tried adding it to the main configuration file appdaemon.yaml and als to apps.yaml in the apps directory both without any effect. Also no extra error messages. What is the correct place to add it?

**Comment by efficiosoft** [comment]
The appdaemon add-on settings page in hassio.

**Comment by taste66** [comment]
Ah totally forgot about that one. That made a diffrent although still not succesful. Now I get this erro```
r
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7c9a8cb70>: Failed to establish a new connection: [Errno -3] Try again',)': /simple/hass-apps/
```
This is what I have in my config
```
{
  "log_level": "info",
  "system_packages": [],
  "python_packages": [
    "hass-apps"
  ]
}
```
And it keeps doing this. I think I will continue tomorrow.

**Comment by efficiosoft** [comment]
You want to install the development version with Schedy included, right? Then you need to use the url to master.zip as described in the guide.

But even with this in place, it should normally download hass-apps stable... Does hassio have internet connectivity?

**Comment by efficiosoft** [comment]
Ah, looks like some strange thing with the server pip tries to connect to... anyway, it'll be gone after switching to the development version.

**Comment by taste66** [comment]
Thanks will look further. I am using an nginx reverse proxy for my docker container so I guess that causes te problem. Will investigate how to solve this.

**Comment by taste66** [comment]
Was a problem with DNS in the docker container. Many solutions are mentioned but this was the only one with did work for my configuration: Ubuntu 16.0 Docker 18.09
https://stackoverflow.com/questions/28668180/cant-install-pip-packages-inside-a-docker-container-with-ubuntu/35277904#

```
For Ubuntu users
You need to add new DNS addresses in the docker config

sudo nano /lib/systemd/system/docker.service
Add the dns after ExecStar.

--dns 10.252.252.252 --dns 10.253.253.253
Should look like that:

ExecStart=/usr/bin/dockerd -H fd:// --dns 10.252.252.252 --dns 10.253.253.253
Then do:

systemctl daemon-reload
sudo service docker restart

```

Can continue now :-)

**Comment by taste66** [comment]
Indeed I could also not believe it but it is reference so many times in relation with the connection problem that I tried it and it worked. Thanks for your assistance.
