### ISSUE TITLE
schedy doesn't work anymore (unexpected error)

### ISSUE THREAD

**Issue by flonair** [efficiosoft/hass-apps#60]
Hi,
since a few days schedy heating doesn't work anymore for me. I checked the configs for "hass-apps" under "python-packages", but that looks fine. 

My log looks like this:

```
2021-04-29 09:34:13.893817 WARNING schedy_heating: ------------------------------------------------------------
2021-04-29 09:34:13.896502 WARNING schedy_heating: Unexpected error running initialize() for schedy_heating
2021-04-29 09:34:13.897578 WARNING schedy_heating: ------------------------------------------------------------
2021-04-29 09:34:13.903610 WARNING schedy_heating: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 161, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_in_executor
    response = future.result()
asyncio.exceptions.TimeoutError
```

**Comment by LukasK13** [comment]
I can confirm this issue with the exact same error message.
I am running schedy / appdaemon in docker and did not change the configuration / version in the last 2 months.

**Comment by LukasK13** [comment]
Upgrading to appdaemon 4.0.8 fixed it for me.

**Comment by LukasK13** [comment]
Updating appdaemon from 4.0.8 to latest fixed the issue for me
